"""
Django settings for postgreVueApi project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4406#ub*cmoy=fta=b9jej2o1mpy03*71w1j@$h$173*8715d2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#povoleni hoste
ALLOWED_HOSTS = [
    '127.0.0.1',
    '127.0.0.1:8080',
    '127.0.0.1:8000',
    'localhost',
    'localhost:8080',
    'localhost:8000',
    ]

#Povoleni hostu pro CORS
CORS_ALLOWED_ORIGINS = [
    'https://127.0.0.1:8080',
    'http://127.0.0.1:8000',
    'https://localhost:8080',
    'http://localhost:8000',
]
# Application definition
# Apliakce, yde se nastavuje jak vztvorena aplikace, tak REST framework a CORS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'vulnerabilityApi'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'postgreVueApi.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'postgreVueApi.wsgi.application'


# Database



#Nastaveni Databaze

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        #nazev databaze
        'NAME': 'vulnerabilityApiDB',
        #prizhlasovaci udaje
        'USER': 'postgres',
        'PASSWORD': 'root',
        #adresa
        'HOST': 'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


#Nastaveni SSL a HSTS, zakomentovane jelikoz defaultni server nepodporuje
#SECURE_SSL_REDIRECT = True
#SECURE_HSTS_SECONDS = 3600
 
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True 

#Nastaveni CSP

CSP_DEFAULT_SRC = ("'none'",)
CSP_STYLE_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_FONT_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'",)


